import os
import httpx

from app.models import EnrichmentRequest, EnrichmentResponse


class GemmaClient:
    def __init__(self) -> None:
        self.base_url = os.getenv("GEMMA_BASE_URL", "http://localhost:8001/v1")
        self.model = os.getenv("GEMMA_MODEL", "google/gemma-3-4b-it")
        self.mode = os.getenv("AI_WORKER_MODE", "mock").lower()

    async def enrich(self, request: EnrichmentRequest) -> EnrichmentResponse:
        if self.mode != "gemma":
            return self._mock_response(request)

        prompt = f"""
You are SpecTrace, an AI assistant for release-risk investigations.

Create concise reviewer-facing output based only on the evidence below.

Investigation title: {request.investigation_title}
Incident description: {request.incident_description}
Detected root cause: {request.root_cause_title}
Root cause details: {request.root_cause_description}
Detected signals: {", ".join(request.detected_signals) or "None"}
Current recommendation: {request.recommendation}
Risk score: {request.risk_score}/100
Confidence: {request.confidence}%

Return plain text with exactly three labeled sections:
REVIEWER SUMMARY:
ENGINEERING RECOMMENDATION:
RELEASE DECISION RATIONALE:
""".strip()

        async with httpx.AsyncClient(timeout=90) as client:
            response = await client.post(
                f"{self.base_url}/chat/completions",
                json={
                    "model": self.model,
                    "messages": [
                        {
                            "role": "system",
                            "content": "You are a precise engineering release-risk analyst.",
                        },
                        {
                            "role": "user",
                            "content": prompt,
                        },
                    ],
                    "temperature": 0.2,
                    "max_tokens": 500,
                },
            )

            response.raise_for_status()
            content = response.json()["choices"][0]["message"]["content"]

        return EnrichmentResponse(
            provider="Gemma",
            mode="amd-gpu",
            reviewer_summary=content,
            engineering_recommendation=request.recommendation,
            release_decision_rationale=(
                "Generated by Gemma from the evidence signals and root-cause context."
            ),
        )

    def _mock_response(self, request: EnrichmentRequest) -> EnrichmentResponse:
        signals = "; ".join(request.detected_signals) or "No high-confidence signals found."

        return EnrichmentResponse(
            provider="SpecTrace local worker",
            mode="mock",
            reviewer_summary=(
                f"Evidence analysis found a likely release regression: "
                f"{request.root_cause_title}. Detected signals: {signals}"
            ),
            engineering_recommendation=request.recommendation,
            release_decision_rationale=(
                f"Risk score {request.risk_score}/100 with "
                f"{request.confidence}% confidence requires human validation "
                f"before release approval."
            ),
        )