"use client";

import { useMemo, useState } from "react";
import {
  CheckCircle2,
  Clipboard,
  Download,
  FileCode2,
  FileText,
  ShieldCheck,
  X,
} from "lucide-react";

type GeneratedAsset = {
  type: string;
  title: string;
  contentPreview: string;
  status: string;
};

type EvidenceItem = {
  id: string;
  sourceType: string;
  sourceReference: string;
  summary: string;
  severity: string;
};

type Props = {
  asset: GeneratedAsset;
  analysisId: string;
  investigationTitle: string;
  rootCauseTitle: string;
  recommendation: string;
  evidence: EvidenceItem[];
  onClose: () => void;
};

function getArtifactIcon(type: string) {
  if (type === "Playwright Test") {
    return <FileCode2 size={18} />;
  }

  if (type === "GitHub Issue") {
    return <FileText size={18} />;
  }

  return <ShieldCheck size={18} />;
}

function getFileName(type: string) {
  if (type === "Playwright Test") {
    return "checkout-confirmation-regression.spec.ts";
  }

  if (type === "GitHub Issue") {
    return "block-release-checkout-confirmation.md";
  }

  return "checkout-release-safety-criteria.md";
}

function normalizeTestName(title: string) {
  return title
    .toLowerCase()
    .replaceAll('"', "")
    .replaceAll("'", "")
    .trim();
}

export default function ArtifactStudio({
  asset,
  analysisId,
  investigationTitle,
  rootCauseTitle,
  recommendation,
  evidence,
  onClose,
}: Props) {
  const [copied, setCopied] = useState(false);

  const content = useMemo(() => {
    const evidenceReferences = evidence
      .map(
        (item) =>
          `- **${item.id} · ${item.sourceType}** — ${item.sourceReference}\n  ${item.summary}`
      )
      .join("\n");

    if (asset.type === "Playwright Test") {
      return `import { test, expect } from "@playwright/test";

test.describe("SpecTrace regression protection", () => {
  test("${normalizeTestName(investigationTitle)}", async ({ page }) => {
    await test.step("Open checkout journey", async () => {
      await page.goto("/checkout");
      await expect(page.getByRole("heading", { name: /checkout/i })).toBeVisible();
    });

    await test.step("Fill payment form", async () => {
      await page.getByLabel("Card number").fill("4242 4242 4242 4242");
      await page.getByLabel("Expiry").fill("12/30");
      await page.getByLabel("CVC").fill("123");
    });

    await test.step("Mock successful payment provider response", async () => {
      await page.route("**/payments/confirm", async (route) => {
        await route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({
            transactionId: "txn_spec_trace_001",
            status: "succeeded",
            amount: 129900,
            currency: "EUR"
          })
        });
      });
    });

    await test.step("Submit payment", async () => {
      await page.getByRole("button", { name: /pay now/i }).click();
    });

    await test.step("Validate confirmation state", async () => {
      await expect(
        page.getByRole("heading", { name: /order confirmed/i })
      ).toBeVisible();

      await expect(page.getByText(/processing payment/i)).not.toBeVisible();
      await expect(page.getByText(/txn_spec_trace_001/i)).toBeVisible();
    });

    await test.step("Protect release decision", async () => {
      await expect(page.getByText(/payment successful/i)).toBeVisible();
      await expect(page.getByText(/confirmation email/i)).toBeVisible();
    });
  });
});

/**
 * SpecTrace context
 * Trace ID: ${analysisId}
 * Root cause: ${rootCauseTitle}
 *
 * Purpose:
 * This regression test protects the checkout confirmation flow from a
 * response-contract mismatch between the frontend and payment service.
 *
 * Evidence:
${evidenceReferences
  .split("\n")
  .map((line) => ` * ${line}`)
  .join("\n")}
 */`;
    }

    if (asset.type === "GitHub Issue") {
      return `# ${investigationTitle}

## Severity
High — customer-impacting checkout regression and release-safety risk.

## Status
Human Approval Required

## SpecTrace Investigation
- **Trace ID:** ${analysisId}
- **Root-cause hypothesis:** ${rootCauseTitle}
- **Generated by:** SpecTrace Evidence Intelligence Platform

## Customer Impact
Customers may complete payment successfully but remain on the processing screen without receiving an order confirmation.

Potential impact:
- Customers may believe payment failed.
- Customers may retry payment and create duplicate-charge risk.
- Support volume may increase.
- Revenue trust may be affected.
- The release should not be approved until the flow is validated.

## Evidence
${evidenceReferences}

## Technical Hypothesis
The frontend checkout confirmation workflow expects a legacy response property, while the payment service returns a newer response contract. The successful provider response is not mapped into the confirmation state.

## Recommended Engineering Action
${recommendation}

## Proposed Fix Plan
1. Confirm the canonical payment response contract.
2. Update the frontend mapper to support the current response field.
3. Preserve backward compatibility if legacy clients still use the old field.
4. Add contract validation between checkout frontend and payment service.
5. Add regression coverage for successful payment confirmation.
6. Validate the complete payment-to-confirmation journey in CI.

## Acceptance Checklist
- [ ] Successful payment response transitions to order confirmation.
- [ ] Processing state disappears after successful payment.
- [ ] The order confirmation page displays a valid transaction/order reference.
- [ ] Regression test covers the current response contract.
- [ ] Contract test prevents future response-field drift.
- [ ] Human reviewer validates the fix before release approval.

## Release Decision
Block release until the regression is fixed, tested, and reviewed.`;
    }

    return `# Release Safety Criteria

## Investigation
- **Trace ID:** ${analysisId}
- **Title:** ${investigationTitle}
- **Root cause:** ${rootCauseTitle}

## Release Gate
The release cannot be approved until the checkout confirmation regression is fixed, tested, and reviewed.

## Scenario 1 — Successful payment confirmation

**Given** a customer has entered valid payment details  
**When** the payment provider returns a successful response  
**Then** the customer must be redirected to the order confirmation state  
**And** the processing state must disappear  
**And** the order reference must be visible to the customer.

## Scenario 2 — Response-contract compatibility

**Given** the payment service returns the current response contract  
**When** the frontend maps the payment confirmation response  
**Then** it must support the canonical transaction identifier  
**And** it must not depend only on a legacy field name.

## Scenario 3 — Regression protection

**Given** the checkout confirmation issue has been fixed  
**When** CI executes the generated Playwright regression test  
**Then** the test must pass before release approval.

## Scenario 4 — Human approval

**Given** the issue affects customer payments and release safety  
**When** the engineering fix is complete  
**Then** a human reviewer must validate the evidence, test result, and release decision before approval.

## Linked Evidence
${evidenceReferences}

## Recommended Action
${recommendation}

## Definition of Done
- [ ] Root-cause hypothesis validated against attached evidence.
- [ ] Frontend/payment response contract aligned.
- [ ] Backward compatibility reviewed.
- [ ] Regression test added to CI.
- [ ] Manual QA confirms successful checkout confirmation.
- [ ] Human reviewer approves release decision.`;
  }, [
    analysisId,
    asset.type,
    evidence,
    investigationTitle,
    recommendation,
    rootCauseTitle,
  ]);

  async function copyContent() {
    await navigator.clipboard.writeText(content);
    setCopied(true);

    window.setTimeout(() => {
      setCopied(false);
    }, 1800);
  }

  function downloadContent() {
    const blob = new Blob([content], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = getFileName(asset.type);
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#020814]/85 p-4 backdrop-blur-md">
      <div className="relative flex max-h-[92vh] w-full max-w-5xl flex-col overflow-hidden rounded-[28px] border border-cyan-200/20 bg-[#071526] shadow-[0_30px_100px_rgba(0,0,0,0.55)]">
        <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-cyan-300 to-transparent" />

        <header className="flex items-start justify-between gap-5 border-b border-white/10 px-6 py-5 sm:px-8">
          <div className="flex gap-4">
            <div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl border border-cyan-300/25 bg-cyan-300/10 text-cyan-200">
              {getArtifactIcon(asset.type)}
            </div>

            <div>
              <p className="text-xs font-bold tracking-[0.16em] text-cyan-300">
                ARTIFACT STUDIO
              </p>

              <h2 className="mt-2 text-xl font-semibold tracking-tight text-white sm:text-2xl">
                {asset.title}
              </h2>

              <p className="mt-2 text-sm text-slate-400">
                Generated from traceable investigation evidence.
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/10 bg-slate-950/60 text-slate-300 transition hover:border-cyan-300/40 hover:text-white"
            aria-label="Close Artifact Studio"
          >
            <X size={18} />
          </button>
        </header>

        <div className="grid min-h-0 flex-1 lg:grid-cols-[1fr_300px]">
          <section className="min-h-0 overflow-auto p-6 sm:p-8">
            <div className="mb-4 flex items-center justify-between gap-4">
              <span className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs font-bold text-cyan-200">
                {asset.type}
              </span>

              <span className="text-xs text-slate-500">
                {asset.status}
              </span>
            </div>

            <pre className="min-h-[420px] overflow-auto rounded-2xl border border-white/10 bg-[#020b17] p-5 font-mono text-xs leading-6 text-slate-200 sm:text-sm">
              <code>{content}</code>
            </pre>
          </section>

          <aside className="border-t border-white/10 bg-gradient-to-b from-cyan-950/20 to-slate-950/30 p-6 lg:border-l lg:border-t-0">
            <p className="text-xs font-bold tracking-[0.15em] text-cyan-300">
              INVESTIGATION CONTEXT
            </p>

            <div className="mt-5 space-y-4">
              <div>
                <span className="block text-xs text-slate-500">Trace ID</span>
                <strong className="mt-1 block font-mono text-xs text-cyan-200">
                  {analysisId}
                </strong>
              </div>

              <div>
                <span className="block text-xs text-slate-500">
                  Evidence sources
                </span>
                <strong className="mt-1 block text-2xl text-white">
                  {evidence.length}
                </strong>
              </div>

              <div className="rounded-xl border border-emerald-300/15 bg-emerald-300/5 p-4">
                <div className="flex items-center gap-2 text-xs font-bold text-emerald-200">
                  <CheckCircle2 size={15} />
                  Evidence-linked draft
                </div>

                <p className="mt-2 text-xs leading-5 text-slate-400">
                  This artifact is generated from the uploaded evidence and
                  current investigation context.
                </p>
              </div>
            </div>
          </aside>
        </div>

        <footer className="flex flex-col gap-3 border-t border-white/10 bg-slate-950/40 px-6 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-8">
          <p className="text-xs text-slate-500">
            Review and validate before exporting to your engineering workflow.
          </p>

          <div className="flex gap-3">
            <button
              type="button"
              onClick={copyContent}
              className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-slate-900 px-4 py-2.5 text-sm font-bold text-slate-200 transition hover:border-cyan-300/35 hover:text-white"
            >
              <Clipboard size={16} />
              {copied ? "Copied" : "Copy"}
            </button>

            <button
              type="button"
              onClick={downloadContent}
              className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan-300 to-sky-400 px-4 py-2.5 text-sm font-extrabold text-slate-950 shadow-[0_10px_28px_rgba(34,211,238,0.22)] transition hover:brightness-110"
            >
              <Download size={16} />
              Download draft
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}
